### PR TITLE
jenkins-code-analysis-flake8 unable to run due to invalid path

### PR DESCRIPTION
**Pull request by tlyng**
Added missing directory seperator for jenkins-code-analysis-flake8 runner.

### CODE REVIEW

**Comment by gforcada** [comment]
Good catch!

Although the way forward is to use plone.recipe.codeanalysis now a days, just FYI :)

**Comment by gforcada** [comment]
@polyester I don't see @tlyng on plone organization, although this contribution is tiny, so no need to sign the contributor agreement right?

**Comment by polyester** [comment]
This is a tiny one, but it would be great if @tlyng would sign contrib agreement

**Comment by tlyng** [comment]
I'll sign one right after office time, I hope it can be processed all digitally? No need to snailmail, fax or something similar?

**Comment by tlyng** [comment]
gforcada, I've not used Plone for about 2 years so I'm a bit rusty. I'm using plone.recipe.codeanalysis for pyramid projects also. The reason I stumbled upon this bug was because I was investigating http://github.com/plone/bobtemplates.plone/ which supplies a jenkins.cfg. Since we're using Jenkins internally here I tried running it and I detected it.

**Comment by tisto** [comment]
@tlyng I just removed jenkins.cfg from bobtemplates.plone (this is still a work in progress) specifically because it currently uses buildout.jenkins. At this point I would not recommend to use buildout.jenkins at all. I know I wrote that stuff, but while using it, I came to the conclusion that making buildouts depend on unversioned files on github is a bad idea. If people need it I can re-add a more sane jenkins.cfg to bobtemplates.plone. Feel free to open an issue there.

**Comment by tlyng** [comment]
@tisto in my case I believe the standard buildout.plonetest plone-x.cfg and qa.cfg are sufficent. If there is something missing it's perhaps documentation and reports which Jenkins can easily consume. I don't believe jshint, csshint and similar belong here at all, it's just prolonging bad css and js development standards in my opinion (I prefer npm, bower and related tools).

**Pull request merged**
